spring:
  ldap:
    embedded:
      ldif: classpath:ldap-server.ldif
      base-dn: dc=dsosedov,dc=com
      port: 8389

ldap:
  url: ldap://localhost:${spring.ldap.embedded.port}/${spring.ldap.embedded.base-dn}
