spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/spring_ldap_db
    username: postgres
  ldap:
    embedded:
      base-dn: dc=dsosedov,dc=com
      ldif: classpath:ldap-server.ldif
      port: 8389

ldap:
  url: ldap://localhost:${spring.ldap.embedded.port}/${spring.ldap.embedded.base-dn}
